dwdstation: P444

pvsetup:
  peakpower: 6.7 # kWp
  efficiencyfactor: 0.8

wash:
  pvthreshold: 2000.0
  basicload: 700.0
  pvtimelimit: 2 # minimum time for pv washing
  basetimelimit: 2 # minimum time for partial pv washing

mqttbroker:
  name: "192.168.0.38"
  port: "1883"
  user: ""
  password: ""
  publishTime: 08:13 # UTC time when to publish new mode value

